# Site settings
title: Aunitz Giménez Mendiburu - Consultor y director de proyectos digitales
subtitle: Aunitz Giménez
header-img: img/home-bg.jpg
email: aunitz@gmail.com
copyright_name: Aunitz Giménez Mendiburu
author: Aunitz Giménez
og_image_index: img/og-image.jpg
baseurl: ""
url: "https://www.aunitz.net"
twitter_username:
#github_username: aunitz
facebook_username:
email_username:
linkedin_username: aunitz
#medium_username: aunitz

# Origen de la plantilla
# https://startbootstrap.com/template-overviews/clean-blog/

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: UA-90648162-1
# Activación de la medición mejorada de Google Analytics 4
google_tracking_id: G-PJWXCNEVTP

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: aunitz

# Build settings
timezone: Europe/Madrid
markdown: kramdown
#highlighter: rouge
#permalink: pretty
permalink: /:title/
paginate: 5
exclude: [".vscode","bootstrap-sass","less","node_modules","package.json","README.md","LICENSE"]

gems: [jekyll-paginate, jekyll-feed, jekyll-redirect-from, jekyll-sitemap]
