# Site settings
title: Aunitz Giménez
header-img: img/home-bg.jpg
email: aunitz@gmail.com
copyright_name: Aunitz Giménez
description: "Más de 17 años en desarrollo web, dirección de proyectos y consultoría tecnológica. Me gustan las soluciones simples a los problemas complejos."
baseurl: ""
url: "http://www.aunitz.net"
twitter_username:
github_username:  aunitz
facebook_username:
email_username:  aunitz@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",resources]

gems: [jekyll-paginate, jekyll-feed]
